defaults: &defaults
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  test:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn add --dev bower purescript pulp
            yarn
            yarn bower install
            yarn build:ci

      - save_cache:
          paths:
            - node_modules
            - bower_components
            - output
          key: deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn jest

  deploy:
    <<: *defaults

    steps:
      - checkout

      - run:
          command: |
            git checkout -b gh-pages
            git reset --hard origin/master

      - restore_cache:
          keys:
          - deps-{{ checksum "example/bower.json" }}-{{ checksum "example/package.json" }}

      - run:
          working_directory: example
          command: |
            yarn add --dev bower purescript pulp
            yarn build

      - save_cache:
          paths:
            - example/node_modules
            - example/bower_components
            - example/output
          key: deps-{{ checksum "example/bower.json" }}-{{ checksum "example/package.json" }}

      - run:
          command: |
            cp docs/* .
            git config user.email "remotenonsense@gmail.com"
            git config user.name "CircleCI"
            git add . && git commit -am 'build gh-pages'
            # https://stackoverflow.com/a/48763205
            git push -q -f https://${GH_PAGES_TOKEN}@github.com/rnons/purescript-html-parser-halogen.git gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy:
          context: gh-pages
          requires:
            - test
          filters:
            branches:
              only:
                - master
